import fs from 'node:fs/promises';
import path from 'node:path';
import { generatedRoot, resolveProjectPath } from './paths.js';
import { readSkillMetadata } from './manifest.js';
import { skillCachePath } from './cache.js';

const CLAUDE_BLOCK_START = '<!-- BAKEFLOW:CLAUDE:START -->';
const CLAUDE_BLOCK_END = '<!-- BAKEFLOW:CLAUDE:END -->';

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function copySupportingFiles(source, target) {
  const entries = await fs.readdir(source, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === 'SKILL.md') continue;
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) {
      await fs.cp(sourcePath, targetPath, { recursive: true });
    } else if (entry.isFile()) {
      await fs.copyFile(sourcePath, targetPath);
    }
  }
}

async function installClaudeSkill(source, target, metadata) {
  await fs.rm(target, { recursive: true, force: true });
  await fs.mkdir(target, { recursive: true });

  const body = await fs.readFile(path.join(source, 'SKILL.md'), 'utf8');
  const skill = [
    '---',
    `name: ${metadata.name}`,
    `description: ${metadata.description || `Use the ${metadata.name} engineering skill.`}`,
    '---',
    '',
    body.trim(),
    '',
  ].join('\n');

  await fs.writeFile(path.join(target, 'SKILL.md'), skill, 'utf8');
  await copySupportingFiles(source, target);
}

async function ensureSymlink(target, linkPath) {
  await fs.rm(linkPath, { recursive: true, force: true });
  await fs.mkdir(path.dirname(linkPath), { recursive: true });
  const relativeTarget = path.relative(path.dirname(linkPath), target);
  await fs.symlink(relativeTarget, linkPath, 'dir');
}

function formatContextSection(projectRoot, context) {
  const entries = Object.entries(context);
  if (entries.length === 0) return 'No project context paths declared.\n';

  return entries
    .map(([name, value]) => {
      const resolved = resolveProjectPath(projectRoot, value);
      return `- ${name}: ${value}\n  Absolute: ${resolved}`;
    })
    .join('\n');
}

async function upsertClaudeMd(projectRoot) {
  const claudeDir = path.join(projectRoot, '.claude');
  const claudeMdPath = path.join(claudeDir, 'CLAUDE.md');
  await fs.mkdir(claudeDir, { recursive: true });

  const block = [
    CLAUDE_BLOCK_START,
    '# Bakeflow Engineering Context',
    '',
    'Before changing this project, read `.engineering/generated/claude-context.md`.',
    'Use the project skills in `.claude/skills/` when the task matches their descriptions.',
    '',
    CLAUDE_BLOCK_END,
    '',
  ].join('\n');

  if (!(await pathExists(claudeMdPath))) {
    await fs.writeFile(claudeMdPath, block, 'utf8');
    return { path: claudeMdPath, status: 'created' };
  }

  const current = await fs.readFile(claudeMdPath, 'utf8');
  const pattern = new RegExp(`${CLAUDE_BLOCK_START}[\\s\\S]*?${CLAUDE_BLOCK_END}\\n?`);
  const next = pattern.test(current)
    ? current.replace(pattern, block)
    : `${current}${current.endsWith('\n') ? '' : '\n'}\n${block}`;
  await fs.writeFile(claudeMdPath, next, 'utf8');
  return { path: claudeMdPath, status: pattern.test(current) ? 'updated' : 'appended' };
}

export async function prepareClaude(projectRoot, manifest, options = {}) {
  const root = generatedRoot(projectRoot);
  const generatedSkillsRoot = path.join(root, 'skills');
  const skillsRoot = path.join(projectRoot, '.claude', 'skills');
  await fs.mkdir(skillsRoot, { recursive: true });
  await fs.mkdir(generatedSkillsRoot, { recursive: true });

  const activeSkills = [];
  for (const [skillName, version] of Object.entries(manifest.skills)) {
    const cached = skillCachePath(skillName, version, options.env);
    if (!(await pathExists(cached))) {
      throw new Error(`Skill "${skillName}@${version}" is not in the local cache. Run \`bakeflow sync\` first.`);
    }

    const metadata = await readSkillMetadata(cached);
    await ensureSymlink(cached, path.join(generatedSkillsRoot, skillName));
    const installPath = path.join(skillsRoot, skillName);
    await installClaudeSkill(cached, installPath, metadata);
    activeSkills.push({ ...metadata, version, path: installPath });
  }

  const contextMd = [
    '# Effective Claude Engineering Context',
    '',
    'Generated by `bakeflow prepare claude`. Do not edit this file by hand.',
    '',
    '## Active Claude Skills',
    '',
    ...activeSkills.map((skill) => `- /${skill.name}: .claude/skills/${skill.name}/SKILL.md`),
    '',
    '## Project Context',
    '',
    formatContextSection(projectRoot, manifest.context),
    '',
    '## Adapter',
    '',
    'Claude Code-compatible context index. Claude should read this file first, then use only the relevant project skills and context files for the current task.',
    '',
  ].join('\n');

  const contextPath = path.join(root, 'claude-context.md');
  await fs.mkdir(root, { recursive: true });
  await fs.writeFile(contextPath, contextMd, 'utf8');
  const claudeMd = await upsertClaudeMd(projectRoot);

  return { contextPath, skillsRoot, activeSkills, claudeMd };
}
