import fs from 'node:fs/promises';
import path from 'node:path';
import { generatedRoot, resolveProjectPath } from './paths.js';
import { readSkillMetadata } from './manifest.js';
import { skillCachePath } from './cache.js';

async function ensureSymlink(target, linkPath) {
  await fs.rm(linkPath, { recursive: true, force: true });
  await fs.mkdir(path.dirname(linkPath), { recursive: true });
  const relativeTarget = path.relative(path.dirname(linkPath), target);
  await fs.symlink(relativeTarget, linkPath, 'dir');
}

async function copyDir(source, target) {
  await fs.rm(target, { recursive: true, force: true });
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.cp(source, target, { recursive: true });
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function formatContextSection(projectRoot, context) {
  const entries = Object.entries(context);
  if (entries.length === 0) return 'No project context paths declared.\n';

  return entries
    .map(([name, value]) => {
      const resolved = resolveProjectPath(projectRoot, value);
      return `- ${name}: ${value}\n  Absolute: ${resolved}`;
    })
    .join('\n');
}

export async function prepareCodex(projectRoot, manifest, options = {}) {
  const root = generatedRoot(projectRoot);
  const skillsRoot = path.join(root, 'skills');
  const installedSkillsRoot = path.join(projectRoot, '.codex', 'skills');
  await fs.mkdir(skillsRoot, { recursive: true });

  const activeSkills = [];
  const installedSkills = [];
  for (const [skillName, version] of Object.entries(manifest.skills)) {
    const cached = skillCachePath(skillName, version, options.env);
    if (!(await pathExists(cached))) {
      throw new Error(`Skill "${skillName}@${version}" is not in the local cache. Run \`bakeflow sync\` first.`);
    }
    const metadata = await readSkillMetadata(cached);
    const linkPath = path.join(skillsRoot, skillName);
    await ensureSymlink(cached, linkPath);

    if (options.installSkills) {
      const installPath = path.join(installedSkillsRoot, skillName);
      await copyDir(cached, installPath);
      installedSkills.push({ name: skillName, version, path: installPath });
    }

    activeSkills.push({ ...metadata, version, path: linkPath });
  }

  const contextMd = [
    '# Effective Engineering Context',
    '',
    'Generated by `bakeflow prepare codex`. Do not edit this file by hand.',
    '',
    '## Active Skills',
    '',
    ...activeSkills.map((skill) => `- ${skill.name}@${skill.version}: .engineering/generated/skills/${skill.name}/SKILL.md`),
    '',
    '## Project Context',
    '',
    formatContextSection(projectRoot, manifest.context),
    '',
    '## Adapter',
    '',
    'Codex-compatible context index. Agents should read this file first, then open only the relevant skill and project context documents for the current task.',
    '',
  ].join('\n');

  const contextPath = path.join(root, 'context.md');
  await fs.writeFile(contextPath, contextMd, 'utf8');

  return { contextPath, skillsRoot, activeSkills, installedSkills };
}
